services:
  event_broker:
    image: drannoc/heyo
    ports:
      - 8022:8022

#   postgres:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: email_history
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
